# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='menumodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.PageModel'),
        ),
    ]
